export const FETCH_PARENTS_ADMIN = "FETCH_PARENTS_ADMIN";
export const FETCH_PARENT_ADMIN = "FETCH_PARENT_ADMIN";
export const DELETE_PARENT_ADMIN = "DELETE_PARENT_ADMIN";

export const FETCH_STUDENTS_ADMIN = "FETCH_STUDENTS_ADMIN";
export const FETCH_STUDENT_ADMIN = "FETCH_STUDENT_ADMIN";
export const DELETE_STUDENT_ADMIN = "DELETE_STUDENT_ADMIN";

export const FETCH_TEACHERS_ADMIN = "FETCH_TEACHERS_ADMIN";
export const FETCH_TEACHER_ADMIN = "FETCH_TEACHER_ADMIN";
export const DELETE_TEACHER_ADMIN = "DELETE_TEACHER_ADMIN";
