export const FETCH_COURSES_ADMIN = "FETCH_COURSES_ADMIN";
export const FETCH_COURSE_ADMIN = "FETCH_COURSE_ADMIN";
export const ADD_COURSE_ADMIN = "ADD_COURSE_ADMIN";
export const UPDATE_COURSE_ADMIN = "UPDATE_COURSE_ADMIN";
export const DELETE_COURSE_ADMIN = "DELETE_COURSE_ADMIN";

export const FETCH_SUBJECTS_ADMIN = "FETCH_SUBJECTS_ADMIN";
export const FETCH_SUBJECT_ADMIN = "FETCH_SUBJECT_ADMIN";
export const ADD_SUBJECT_ADMIN = "ADD_SUBJECT_ADMIN";
export const UPDATE_SUBJECT_ADMIN = "UPDATE_SUBJECT_ADMIN";
export const DELETE_SUBJECT_ADMIN = "DELETE_SUBJECT_ADMIN";

export const FETCH_PARENTS_ADMIN = "FETCH_PARENTS_ADMIN";
export const FETCH_PARENT_ADMIN = "FETCH_PARENT_ADMIN";
export const ADD_PARENT_ADMIN = "ADD_PARENT_ADMIN";
export const UPDATE_PARENT_ADMIN = "UPDATE_PARENT_ADMIN";
export const DELETE_PARENT_ADMIN = "DELETE_PARENT_ADMIN";

export const FETCH_STUDENTS_ADMIN = "FETCH_STUDENTS_ADMIN";
export const FETCH_STUDENT_ADMIN = "FETCH_STUDENT_ADMIN";
export const ADD_STUDENT_ADMIN = "ADD_STUDENT_ADMIN";	
export const UPDATE_STUDENT_ADMIN = "UPDATE_STUDENT_ADMIN";
export const DELETE_STUDENT_ADMIN = "DELETE_STUDENT_ADMIN";

export const FETCH_TEACHERS_ADMIN = "FETCH_TEACHERS_ADMIN";
export const FETCH_TEACHER_ADMIN = "FETCH_TEACHER_ADMIN";
export const ADD_TEACHER_ADMIN = "ADD_TEACHER_ADMIN";
export const UPDATE_TEACHER_ADMIN = "UPDATE_TEACHER_ADMIN";
export const DELETE_TEACHER_ADMIN = "DELETE_TEACHER_ADMIN";
