export const family = {
  idFamily: "2fj2fj98j3gjf",
  parents: [
    { id: "2910fj218jf2", tipo: "apoderado", nombres: "Emma", apellidos: "Tapia" },
    { id: "j3fj9238j4gj9823", tipo: "apoderado",nombres: "Juan", apellidos: "Rojas" }
  ],
  students: [
    {
    id: "12412c1923m1928dj20d29",
    id_colegio: "29183080jf102k9dk",
    tipo: 'estudiante',
    nombres: "Marcelo Jose",
    apellidos: "Rojas Tapia",
    rut: "20539858-5",
    curso: "2do Medio",
    notas: [
      {
        fecha: '2022-09-02',
        asignatura: 'Matemáticas',
        evaluacion: 'Prueba 1 Matemáticas',
        nota: 5.5,
        ponderacion: 0.3,
      },
      {
        fecha: '2022-09-03',
        asignatura: 'Matemáticas',
        evaluacion: 'Prueba 2 Matemáticas',
        nota: 6.5,
        ponderacion: 0.4,
      },
      {
        fecha: '2022-09-04',
        asignatura: 'Matemáticas',
        evaluacion: 'Prueba 3 Matemáticas',
        nota: 7,
        ponderacion: 0.3,
      },
      {
        fecha: '2022-09-06',
        asignatura: 'Lenguaje',
        evaluacion: 'Prueba 1 Lenguaje',
        nota: 5,
        ponderacion: 0.3,
      },
      {
        fecha: '2022-09-07',
        asignatura: 'Historia',
        evaluacion: 'Prueba 1 Historia',
        nota: 6,
        ponderacion: 0.3,
      },
      {
        fecha: '2022-09-08',
        asignatura: 'Historia',
        evaluacion: 'Prueba 2 Historia',
        nota: 5.5,
        ponderacion: 0.4,
      },
      {
        fecha: '2022-09-09',
        asignatura: 'Lenguaje',
        evaluacion: 'Prueba 2 Lenguaje',
        nota: 4,
        ponderacion: 0.4,
      },
      {
        fecha: '2022-09-10',
        asignatura: 'Lenguaje',
        evaluacion: 'Prueba 3 Lenguaje',
        nota: 3.5,
        ponderacion: 0.3,
      },
      {
        fecha: '2022-09-11',
        asignatura: 'Ingles',
        evaluacion: 'Prueba 1 Inglés',
        nota: 1.5,
        ponderacion: 0.3,
      },
      {
        fecha: '2022-10-07',
        asignatura: 'Ingles',
        evaluacion: 'Prueba 2 Inglés',
        nota: 7,
        ponderacion: 0.4,
      },
      {
        fecha: '2022-10-08',
        asignatura: 'Ingles',
        evaluacion: 'Prueba 3 Inglés',
        nota: 6.5,
        ponderacion: 0.3,
      },
      {
        fecha: '2022-11-09',
        asignatura: 'Ciencias',
        evaluacion: 'Prueba 1 Ciencias',
        nota: 4.5,
        ponderacion: 0.3,
      },
      {
        fecha: '2022-11-10',
        asignatura: 'Ciencias',
        evaluacion: 'Prueba 2 Ciencias',
        nota: 6,
        ponderacion: 0.7,
      },
      {
        fecha: '2022-11-11',
        asignatura: 'Ed. Física',
        evaluacion: 'Prueba 1 Ed. Física',
        nota: 5,
        ponderacion: 1,
      }],
    },
    {
    id: "1892381293812",
    id_colegio: "29183080jf102k9dk",
    tipo: 'estudiante',
    nombres: "Gonza Matias",
    apellidos: "Donoso Días",
    rut: "19249858-5",
    curso: "1ro Básico",
    notas: [
      {
        fecha: '2022-09-02',
        asignatura: 'Matemáticas',
        evaluacion: 'Prueba 1 Ciencias Naturales',
        nota: 6,
        ponderacion: 0.3,
      },
      {
        fecha: '2022-09-03',
        asignatura: 'Ciencias Naturales',
        evaluacion: 'Prueba 2 Ciencias Naturales',
        nota: 5,
        ponderacion: 0.4,
      },
      {
        fecha: '2022-09-04',
        asignatura: 'Ciencias Naturales',
        evaluacion: 'Prueba 3 Ciencias Naturales',
        nota: 5.7,
        ponderacion: 0.3,
      },
      {
        fecha: '2022-09-06',
        asignatura: 'Lenguaje',
        evaluacion: 'Prueba 1 Taller',
        nota: 7,
        ponderacion: 1,
      },
      {
        fecha: '2022-09-07',
        asignatura: 'Historia',
        evaluacion: 'Prueba 1 Historia',
        nota: 6,
        ponderacion: 0.3,
      },
      {
        fecha: '2022-09-08',
        asignatura: 'Historia',
        evaluacion: 'Prueba 2 Historia',
        nota: 5.5,
        ponderacion: 0.4,
      },
      {
        fecha: '2022-09-11',
        asignatura: 'Ingles',
        evaluacion: 'Prueba 1 Inglés',
        nota: 1.5,
        ponderacion: 0.3,
      },
      {
        fecha: '2022-10-07',
        asignatura: 'Ingles',
        evaluacion: 'Prueba 2 Inglés',
        nota: 7,
        ponderacion: 0.4,
      },
      {
        fecha: '2022-10-08',
        asignatura: 'Ingles',
        evaluacion: 'Prueba 3 Inglés',
        nota: 6.5,
        ponderacion: 0.3,
      },
      {
        fecha: '2022-11-09',
        asignatura: 'Ciencias',
        evaluacion: 'Prueba 1 Ciencias',
        nota: 4.5,
        ponderacion: 0.3,
      },
      {
        fecha: '2022-11-10',
        asignatura: 'Ciencias',
        evaluacion: 'Prueba 2 Ciencias',
        nota: 6,
        ponderacion: 0.7,
      },
      {
        fecha: '2022-11-11',
        asignatura: 'Ed. Física',
        evaluacion: 'Prueba 1 Ed. Física',
        nota: 5,
        ponderacion: 1,
      }],
    }
  ]
}